spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: "jdbc:mysql://localhost:3306/pass_local"
    username: "root"
    password: "qp4400pv!@"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
